### ISSUE TITLE
Tag the master branch as 1.0.1

### ISSUE THREAD

**Issue by franquis** [ferjul17/Sellsy-api#10]
As the current release 1.0.0 print logs to STDOUT (see  #5), is there any possibility to tag the master branch as 1.0.1 ?
Thanks

**Comment by ferjul17** [comment]
Hi, yes you're right. I wanted to do some more modifications before
releasing a new version but I don't have much time to do it now. I released
a 1.0.1 version.

Regards,

Julien

2016-11-22 17:36 GMT+01:00 Franquis notifications@github.com:

**Comment by franquis** [comment]
Thanks !
