### ISSUE TITLE
oauth_problem=nonce_used... again

### ISSUE THREAD

**Issue by ZeCharger** [ferjul17/Sellsy-api#11]
ferjul17 commented on 1 Jan 2016
Sometimes Sellsy return oauth_problem=nonce_used. I have the change how the nonce is generated.
--> bug closed

Hi ferjul,
please, on the next milestone, put an higher rand range... to avoid the problem again ;)
Thx

-->sellsy-client\src\Client\Client.php line 301
-->'oauth_nonce' => \md5($now->getTimestamp() + \rand(0, 1000000)),

**Comment by ferjul17** [comment]
Hi,

This issue was fix one year ago. I think you are not using the lastest version of the lib.

Regards
