### ISSUE TITLE
Listing documents using a saved search

### ISSUE THREAD

**Issue by ghost** [ferjul17/Sellsy-api#12]
Hi !
I'm trying to use the "List documents using a search ID" feature fo the sellsy API.
https://api.sellsy.com/documentation/methods#listingsettingsearchlisting

When I do this : 

```php
$promise = $client->getService('Document')->callAsync('search', ['savedSearchId'=> '12345'])->then(function($res) {
	    var_dump($res);
});
```
But I get this error : 

( ! ) Fatal error: Uncaught exception 'SellsyApi\Exception\SellsyError' with message 'Method Document.search does not exist' in C:\wamp64\www\sellsy-api-ferjul17\vendor\ferjul17\sellsy-api\src\Request\Request.php on line 249
--

How can I do it correctly ?

**Comment by ferjul17** [comment]
Bonjour Adrien,

Comme le message l'indique, la méthode search du service Document n'existe pas dans Sellsy. 
Leur doc est assez mal fichu...
Il faut plutôt utiliser cette API: https://api.sellsy.fr/documentation/methodes#documentgetlist

**Comment by ghost** [comment]
Mais pourtant, d'après cette même documentation, la méthode listingsettingsearchlisting existe bien non ?
J'ai du mal à saisir.

**Comment by ferjul17** [comment]
Dans le code que tu me montes tu appels la méthode `search` du service `Document`. Ça n'existe pas.

La doc que tu me donnes pointe sur quelque chose de mal défini par Sellsy. 

```php
$request = array(
    'params' => array(
        'search'    => array(
			'savedSearchId' => {{savedSearchId}}
		)
	)
);
$response = sellsyConnect::load()->requestApi($request);
```

Il ne précise pas le champ `method` comme pour les autres appels. Avec l'URL, on peut penser qu'il s'agit de la méthode searchListing du service ListingSettings mais aucun moyen de le savoir.

Le plus simple serait de voir directement avec eux.

**Comment by ghost** [comment]
Ok... Je vais les appeler.

**Comment by adrienbuffet** [comment]
J'ai compris...
En réalité, la documentation de cette "fonctionnalité" n'est qu'une partie de la requête présente dans les différentes méthodes.

Il faut donc utiliser la méthode associé à chacun d'entre eux.
Par exemple, pour avoir la liste des devis (en utilisant le filtre de recherche préenregistré...)
Il faut faire : 

```php
	$promise = $client->getService('Document')->callAsync('getList', ['doctype' => 'estimate', 'search' => ['savedSearchId' => '12345']])->then(function($res) {
var_dump($res);
	});
```

Et là, ça marche :)

**Comment by ghost** [comment]
J'ai compris.. En fait, il faut juste remplacer le contenu de 'search' de cette "fonctionnalité" dans la methode getList de Document... Et là, ça fonctionne...

```php
	$promise = $client->getService('Document')->callAsync('getList', ['doctype' => 'estimate', 'search' => ['savedSearchId' => '12345']])->then(function($res) {
	    var_dump($res);
	});
```
