### ISSUE TITLE
can anyone help me with the file upload in product ?

### ISSUE THREAD

**Issue by pratikraman-dev** [ferjul17/Sellsy-api#14]
i want to upload images into product gallery and im getting 

do_file is missing 

can anyone please help me to upload images in products

![image](https://user-images.githubusercontent.com/8825570/79036109-873d7a80-7be2-11ea-96c5-8a59d0f70017.png)

im using the catalouge.addimagetogallery

![image](https://user-images.githubusercontent.com/8825570/79036153-0fbc1b00-7be3-11ea-9fa9-f6f22ee67b51.png)

**Comment by t-prod** [comment]
Hi,

Do you resolve this ? I think there's no way to upload a file through this package. You must have a curlfile instance implemented in our new curl connector class. 
Maybe you found an other solution ?

Regards
