### ISSUE TITLE
oauth_problem=nonce_used

### ISSUE THREAD

**Issue by ferjul17** [ferjul17/Sellsy-api#4]
Sometimes Sellsy return oauth_problem=nonce_used. I have the change how the nonce is generated.

**Comment by ZeCharger** [comment]
Hi ferjul,
please, on the next milestone, put an higher rand range... to avoid the problem again ;)
Thx

-->sellsy-client\src\Client\Client.php line 301
-->'oauth_nonce' => \md5($now->getTimestamp() + \rand(0, 1000000)),
