### ISSUE TITLE
custom logs

### ISSUE THREAD

**Issue by ferjul17** [ferjul17/Sellsy-api#5]
It would be nice if we can provide an object / callable which handle logging instead of just printing it

**Comment by k1n0b0n** [comment]
Or at least the ability to disable logging...

**Comment by ferjul17** [comment]
Yeah, I'll definitely offer this possibility. I'll do that next month.

2016-08-22 17:13 GMT+02:00 Maxime notifications@github.com:

**Comment by k1n0b0n** [comment]
you can use php functions 
- ob_start()
- ob_end_clean()

to prevent printing what's in between them.
