### ISSUE TITLE
help please : redirect ko with getService

### ISSUE THREAD

**Issue by Urbannet** [ferjul17/Sellsy-api#7]
Hello Julien,

My action is :

``` php
    public function actionInvoice($id)
    {
        $model = $this->findModel($id);
        $client = new Client(['userToken'      => 'fbf845269f7..b8', 'userSecret'     => 'c..7edfe2',
                'consumerToken'  => 'd..09d9b', 'consumerSecret' => '7db4..09c',
        ]);
        $docId = $client->getService('Document')->call('create', [
                'document' => array(
                        'doctype'   => 'invoice',
                        'thirdid'   => '6074622',
                        'subject'   => 'ppppppppp'
                )
        ])['doc_id'];

        $model->num_facture_sellsy='aaaaa'; //.$docId;              
        $model->save();     
        return $this->redirect(['missions/user']);
    }
```

When i comment 
    $docId = $client->getService('Document')->call('create', [
                'document' => array(
                        'doctype'   => 'invoice',
                        'thirdid'   => '6074622',
                        'subject'   => 'ppppppppp'
                )
        ])['doc_id'];

I have good redirection, but with the latter code redirects me to another action.

your help please

Thank you

**Comment by ferjul17** [comment]
I'm sorry but I dont get what's your issue.

**Comment by Urbannet** [comment]
Thank's for all.
I asked the question on the forum
http://www.yiiframework.com/forum/index.php/topic/70978-sellsy-api-redirections-differents-entre-local-et-en-ligne/

**Comment by Urbannet** [comment]
Thank you for all, 

I turn off the display of the debug (Request.php), the message will display more and I have good redirection. thanks again
