### ISSUE TITLE
"invoice" doctype is invalid

### ISSUE THREAD

**Issue by Urbannet** [ferjul17/Sellsy-api#8]
Help please,

$promise = $client->getService('Document')->callAsync('getPublicLink', [
                'document' => array(
                        'doctype' => 'invoice',
                        'docid' => '3773800',
                )
        ])->then(function($res) {
            var_dump($res);  
        });
            $promise->wait();

With PHP normal, i use "invoice" and it s ok, with your plugin he told me doctype is invalid.

Your help please

Thank's

**Comment by ferjul17** [comment]
Urbannet, for these kind of error, you must ask to Sellsy directly. If you read the documentation, you can see that you did a mistake in the params. remove the level "document" and it should work:

``` php
$client->getService('Document')->callAsync('getPublicLink', [
'doctype' => 'invoice',
'docid' => '3773800',
]);
```

**Comment by Urbannet** [comment]
Thank you It work's.
I apologize for the inconvenience, I am beginner.
If you allow one last question, why I have the result that appears on my screen, for example
`$client->getService('Document')->call('getPublicLink', [
        'doctype' => 'invoice',
        'docid' => $this->num_facture_sellsy,
    ]);`

[5742363b0c8c9]2016-05-23T00:44:11+02:00 --> {"method":"Document.getPublicLink","params":{"doctype":"invoice","docid":"3775223"}} [5742363b0c8c9]2016-05-23T00:44:12+02:00 <-- "?_f=file&id=JTBDJUM1UkwlMjJGJTVCViVBNyV

**Comment by ferjul17** [comment]
Yes, I know, I have to implement something to let you decide what you want to do with the logs. It will be fixed in the next release.
If you don't want to see the logs, you can comment out the lines 157 and 167 in src/Request/Request.php

**Comment by Urbannet** [comment]
Thank you for all, 

I turn off the display of the debug (Request.php), the message will display more and I have good redirection. thanks again
